### PR TITLE
Helmfile update pr

### PR DESCRIPTION
**Pull request by wagmarcel**

### CODE REVIEW

**Comment by sysarcher** [comment]
@wagmarcel which charts should I focus on?

The flink charts are giving me some linting errors:

```
$ helm lint flink 
==> Linting flink
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist
[ERROR] templates/: template: flink/templates/taskmanager-session-deployment.yaml:7:22: executing "flink/templates/taskmanager-session-deployment.yaml" at <.Values.flink.taskmanagers>: nil pointer evaluating interface {}.taskmanagers

Error: 1 chart(s) linted, 1 chart(s) failed
```

Maybe we should add the Helm3 linter to our CI??

**Comment by sysarcher** [comment]
All the lints:

```
$ helm lint *
==> Linting alerta
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: alerta/templates/deployment.yaml:32:31: executing "alerta/templates/deployment.yaml" at <.Values.keycloak.alertaClientSecret>: nil pointer evaluating interface {}.alertaClientSecret

==> Linting cert-manager
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist
[ERROR] templates/: template: cert-manager/templates/cert-self.yaml:10:24: executing "cert-manager/templates/cert-self.yaml" at <.Values.certmanager.secret>: nil pointer evaluating interface {}.secret

==> Linting flink
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist
[ERROR] templates/: template: flink/templates/taskmanager-session-deployment.yaml:7:22: executing "flink/templates/taskmanager-session-deployment.yaml" at <.Values.flink.taskmanagers>: nil pointer evaluating interface {}.taskmanagers

==> Linting kafka
[INFO] Chart.yaml: icon is recommended

==> Linting keycloak
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: keycloakOperator/templates/realmjob.yaml:49:27: executing "keycloakOperator/templates/realmjob.yaml" at <.Values.keycloak.internalAuthService.name>: nil pointer evaluating interface {}.internalAuthService

==> Linting minio
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist

==> Linting postgres
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: postgresOperator/templates/minimal-postgres-manifest.yaml:7:20: executing "postgresOperator/templates/minimal-postgres-manifest.yaml" at <.Values.db.teamId>: nil pointer evaluating interface {}.teamId

==> Linting scorpio
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: scorpioBroker/templates/subscription-manager-deployment.yaml:34:29: executing "scorpioBroker/templates/subscription-manager-deployment.yaml" at <.Values.keycloak.externalAuthService.protocol>: nil pointer evaluating interface {}.externalAuthService

Error: 8 chart(s) linted, 6 chart(s) failed
```

**Comment by wagmarcel** [comment]
> All the lints: https://pastebin.com/x46nYxEg

Thanks - yes one reason is that we use now helmfile which is a "helm" metalayer, describing the dependencies an joint values. That makes the values.yaml files sometimes unneccessary. But I agree, linting is a good idea, should be `helmfile lint` though. But it shows similar errors. Will work on fixing it.

**Comment by wagmarcel** [comment]
@sysarcher  ok - helmfile lint runs through now - actually I realized that the flink & minio charts were not supposed to be released, I accidentally pushed the flink update to the wrong branch...
Do you want to add the linting test?

**Comment by sysarcher** [comment]
> @sysarcher  ok - helmfile lint runs through now - actually I realized that the flink & minio charts were not supposed to be released, I accidentally pushed the flink update to the wrong branch...
> Do you want to add the linting test?

Yup. I'll add the Lints to CI.

**Comment by wagmarcel** [comment]
@sysarcher can you then please approve?

**Review by sysarcher — APPROVED** [review]
LGTM

Will add lint in a different PR

**Pull request merged**
